### ISSUE TITLE
Error: No node found for selector: *[name=email]

### ISSUE THREAD

**Issue by clarako** [thomascullen/airtable-graphql#5]
Hi,

When I run `airtable-graphql pull --email=[your_email] --password=[your_password] --base=[base_id]`

I get the this error:
```
Fetching schema...
(node:11195) UnhandledPromiseRejectionWarning: Error: No node found for selector: *[name=email]
    at assert (/Users/clarako/.npm-global/lib/node_modules/airtable-graphql/node_modules/puppeteer/lib/helper.js:229:11)
    at DOMWorld.type (/Users/clarako/.npm-global/lib/node_modules/airtable-graphql/node_modules/puppeteer/lib/DOMWorld.js:426:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (/Users/clarako/.npm-global/lib/node_modules/airtable-graphql/node_modules/puppeteer/lib/helper.js:108:27)
    at Page.type (/Users/clarako/.npm-global/lib/node_modules/airtable-graphql/node_modules/puppeteer/lib/Page.js:1054:29)
    at module.exports (/Users/clarako/.npm-global/lib/node_modules/airtable-graphql/fetchSchema.js:8:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please help.

Thank you.

**Comment by clarako** [comment]
I figured out I used the wrong baseId. Sorry about this.
The error was not really clear. But I figured it out.
